CREATE TABLE CANDIDAT
(
	CANDIDAT_ID INT IDENTITY(1,1) PRIMARY KEY,
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NOT NULL,
	PHONE_NUMBER NVARCHAR(15) NULL,
	EMAIL NVARCHAR(100) UNIQUE,
	TIME_INTERVAL NVARCHAR(20) NULL,
	LINKEDIN_PROFIL_URL NVARCHAR(500) NULL,
	GITHUB_PROFIL_URL NVARCHAR(500) NULL,
	TEXT_COMMENT NVARCHAR(1000) NOT NULL,
)